### ISSUE TITLE
Annual Leave Counter In Ethiopian Calender

### ISSUE THREAD

**Issue by eyasuashenafi** [andegna/calender#39]
Hi, I'm Asking that if you have any function on annual leave counter starting from "starting date " and store the Date that you have in each year

**Comment by SamAsEnd** [comment]
"annual leave counter" is **out of the scope** for this package.

**Comment by SamAsEnd** [comment]
Check the documentation at [https://andegna.github.io/calender/](https://andegna.github.io/calender/) to see what this package provides.
